export const BRANDING = {
  companyName: 'PrincePerelson & Associates',
  appTitle: 'PrincePerelson Recruiting Email Builder',
  primaryColor: '#1b2d4b',
  secondaryColor: '#8a7158',
  slateColor: '#46556f',
  borderColor: '#d5cdbd',
  canvasColor: '#ede9e0',
  cardColor: '#fbf8f1',
  logoPrimaryPath: '/assets/logos/ppa-logo-primary.svg',
  logoMarkPath: '/assets/logos/ppa-logo-mark.svg',
  websiteUrl: 'https://www.princeperelson.com',
  emailFontStack: "'Montserrat', Arial, Helvetica, sans-serif",
  appFontFamily: "'Montserrat', Arial, Helvetica, sans-serif",
} as const;
